name: Docker Build and Push, Kubernetes deploy

on:
  push:
    branches:
    - '!main'
  pull_request:
    - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build --tag levelupdevops-pr:${{ github.sha }} .
